name: Integration Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Integration:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
    env:
      SECRET_KEY: simple-secret-key-to-tests

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry config virtualenvs.create false
          make dependencies

      - name: Run Checks
        run: |
          make integration-pipeline-local
        
  Deploy:
    needs: Integration
    runs-on: ubuntu-latest
    env: 
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Build, Push docker and Release
        run: |
          heroku container:login 
          heroku container:push -a reseller-cashback web 
          heroku container:release -a reseller-cashback web 
          heroku run -a reseller-cashback ./deployment-tasks.sh 