# Generated by Django 3.2.8 on 2021-10-28 18:58

import uuid

import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderModel',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Created at'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Updated at'
                    ),
                ),
                (
                    'code',
                    models.CharField(max_length=256, verbose_name='Code'),
                ),
                (
                    'value',
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=20,
                        verbose_name='Total value',
                    ),
                ),
                (
                    'cpf_reseller',
                    localflavor.br.models.BRCPFField(
                        max_length=14, verbose_name='CPF'
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('in_validation', 'In validation'),
                            ('approved', 'Approved'),
                        ],
                        default='in_validation',
                        max_length=20,
                        verbose_name='Status',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Sales Order',
                'verbose_name_plural': 'Sales Orders',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
